select * from customer_data

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customer_data group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
--to find avgerage
--select avg(purchase_amount)::numeric(10,2) from customer_data;
--to find only discount _applied customers..
--select customer_id,age,category from customer_data where discount_applied='Yes';

select customer_id,age,category,discount_applied from customer_data where discount_applied='Yes' 
and purchase_amount>=(select avg(purchase_amount)::numeric(10,2) from customer_data)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating)::numeric(10,2) as "avg_rating" 
from customer_data group by item_purchased
order by avg(review_rating) desc limit 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select * from customer_data

--select purchase_amount,shipping_type from customer_data

select shipping_type ,avg(purchase_amount) from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type 


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

--select distinct(subscription_status) fc
--select subscription_status,count(*) from customer_data group by subscription_status
select *from customer_data

select subscription_status,count(customer_id) as cumstomers ,avg(purchase_amount)::numeric(10,5) as average_spend,
sum(purchase_amount) as total_spend 
from customer_data
group by subscription_status
order by total_spend,average_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?




SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with segment as(
select customer_id,previous_purchases,
case when previous_purchases =1 then 'new'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
		end as customer_segment
		from customer_data
)
select customer_segment,count(*) as num_customers from segment
group by customer_segment;

--select distinct(previous_purchases) from customer_data
--select min(previous_purchases),max(previous_purchases) from customer_data


--Q8. What are the top 3 most purchased products within each category? 



WITH item_data AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_data
WHERE item_rank <=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select *from customer_data


SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 

select age_group,sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc
 